apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: elearning-platform

build:
  artifacts:
    - image: elearning-platform/monolith
      context: ./monolith
      docker:
        dockerfile: Dockerfile
    - image: elearning-platform/web-app
      context: ./apps/web-app
      docker:
        dockerfile: Dockerfile
    - image: elearning-platform/admin-portal
      context: ./apps/admin-portal
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}

deploy:
  helm:
    releases:
      - name: elearning-platform
        chartPath: ./helm/elearning-platform
        valuesFiles:
          - ./helm/elearning-platform/values.yaml
        setValues:
          image.tag: "{{.DIGEST}}"
        wait: true
        upgradeOnChange: true
        recreatePods: true
        overrides:
          imagePullSecrets:
            - name: regcred

profiles:
  - name: dev
    build:
      local: {}
    deploy:
      helm:
        releases:
          - name: elearning-platform
            valuesFiles:
              - ./helm/elearning-platform/values.yaml
              - ./helm/elearning-platform/values-dev.yaml
            setValues:
              image.tag: dev

  - name: prod
    build:
      googleCloudBuild: {}
    deploy:
      helm:
        releases:
          - name: elearning-platform
            valuesFiles:
              - ./helm/elearning-platform/values.yaml
              - ./helm/elearning-platform/values-production.yaml
            setValues:
              image.tag: prod 