apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - service-account.yaml
  - rbac.yaml

commonLabels:
  app: elearning-platform

commonAnnotations:
  description: E-Learning Platform
  version: v1.0.0 